language: c
script: ./travis-tool.sh run_tests
before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  - ./travis-tool.sh r_binary_install rgl RANN igraph filehash digest testthat
  - ./travis-tool.sh install_github jefferis/nat
  - bash <(wget -q -O- http://neuro.debian.net/_files/neurodebian-travis.sh)
  - sudo apt-get install cmtk --no-install-recommends
install:
  - ./travis-tool.sh install_deps
notifications:
  email:
    on_success: change
    on_failure: change
env:
  global:
    - secure: f3wCk5rXHy6ghYxDeo2hQ/GMHB3dus155XurN0GVLTxopcnQTbHbuQfv4T0vOYDY28LyLhu++EOybbUW3H3Ctnsjw/XBA7FA9XIqFJ5cLuwj1fYR6dVwDl1eDLOCtBjGQq+Fh8OxmDMNnN/EOx7OWhwJJWaHgtD4Kdf8Z9wp/6A=
    - WARNINGS_ARE_ERRORS=1
    - _R_CHECK_FORCE_SUGGESTS_=0
after_success:
  - chmod 755 ./travisbuildchildren.sh
  - ./travisbuildchildren.sh
