language: r
sudo: required
cache:
  packages: true
  directories:
  - $HOME/usr/local
warnings_are_errors: true
before_install:
  - curl -OL https://raw.githubusercontent.com/jefferis/nat/master/build-cmtk.sh
  - bash build-cmtk.sh
before_script:
  - export PATH=$PATH:$HOME/usr/local/bin
r_github_packages:
  - jimhester/covr
env:
  global:
    - secure: enuHyjS3QdAyNTn03zj2sL4jbAh1pJ7vzCC4m674KdTG0tYB7ApiLEiu/PxT88Ub4UficJtutas3qLHhOpjL6ZW/Z18RYRIzwGHwimvVMRLYg2G1R8BPgsWtMSA3GynlOCHjiFxLeoGPW0mPJ4+5wzWJXD6tKWvZPHOngki/658=
    - RGL_USE_NULL=TRUE
after_success:
  - Rscript -e 'library(covr);coveralls(exlusions="R/zzz.R")'
  - bash travisbuildchildren.sh
